-- NOTE:
-- Some environments run with a DB role that is not the owner of this table,
-- so ALTER TABLE can fail with: "must be owner of table email_subscribers".
-- We intentionally keep this migration as a no-op to avoid startup failure.
--
-- Topic separation is handled at the application layer using the `source` field.
